name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: 52.47.136.75
          username: root
          password: 1oko*g4aYD8O6jyR
          script: |
            cd /var/www/www-root/data/www/fungaid.com
            git pull
            npm run build
            pm2 restart fungaid.com